# Generated by Django 2.2 on 2022-01-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
    ]
